version: "3"
services:
  hub:
    image: seleniarm/hub:4.20
    ports:
    - 4444:4444
    # - 4442:4442
    # - 4443:4443
  chrome:
    image: seleniarm/node-chromium:latest
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
   
  firefox:
    image: seleniarm/node-firefox:latest
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443