pipeline{
    agent {
        docker {
            image "alpine"
        }
    }

    stages{
        stage('access google home-1'){
            steps{
                sh "wget www.google.com"
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'index.html', followSymlinks: false
        }
    }
}
