pipeline{
    agent none

    stages{
        stage('Build jar'){
            agent {
                docker {
                    image 'maven:latest'
                    args '-u root -v /tmp/m2:/root/.m2'
                }
            }
            steps{
                sh "mvn clean package -DskipTests"
            }
        }
        stage('Build Image'){
            steps{
                script {
                    app = docker.build('rashmisoundar/selenium')
                }
            }
        }
        stage('Push Image'){
            steps {
                script {
                    // registry url is blank for docker hub is usigng aws give that
                    docker.withRegistry('','dockerhub-creds'){
                        app.push("latest")
                    }
                }
            }
        }

    post{
        always{
            sh "docker logout"
        }
    }
}
}